// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nftogqaflkkyqqqenywl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mdG9ncWFmbGtreXFxcWVueXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MjY3NTEsImV4cCI6MjA3MzAwMjc1MX0.SOrafVPb0XZTPdcMFTtqTLSvT5J1Z1M-39I53ULWNCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});